language: go

go:
  - tip

install:
  - go get github.com/wm/go-flowdock/flowdocki
  - go get code.google.com/p/go.tools/cmd/cover
  - go get -u github.com/mattn/goveralls

script:
  - goveralls -coverprofile=profile.cov -service=travis-ci
